# Generated by Django 4.0.5 on 2022-07-07 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=40)),
                ('init', models.IntegerField(blank=True, default=0, null=True)),
                ('kneader', models.IntegerField(blank=True, default=0, null=True)),
                ('end_extruder', models.IntegerField(blank=True, default=0, null=True)),
                ('end_prepress', models.IntegerField(blank=True, default=0, null=True)),
                ('start_prim_press', models.IntegerField(blank=True, default=0, null=True)),
                ('end_prim_press', models.IntegerField(blank=True, default=0, null=True)),
                ('steam_in', models.IntegerField(blank=True, default=0, null=True)),
                ('start_sec_press', models.IntegerField(blank=True, default=0, null=True)),
                ('start_sec_press2', models.IntegerField(blank=True, default=0, null=True)),
                ('cooling', models.IntegerField(blank=True, default=0, null=True)),
                ('record_sec_press', models.IntegerField(blank=True, default=0, null=True)),
                ('record_sec_press2', models.IntegerField(blank=True, default=0, null=True)),
                ('end_sec_press', models.IntegerField(blank=True, default=0, null=True)),
                ('extra1', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField(blank=True, default=0, null=True)),
                ('run_no', models.IntegerField(blank=True, default=0, null=True)),
                ('mc_no', models.IntegerField(blank=True, default=0, null=True)),
                ('kneader_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89022))),
                ('end_extruder_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('end_prepress_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('start_prim_press_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('end_prim_press_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('stream_in_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('start_sec_press_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('start_sec_press2_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('cooling_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('record_sec_press_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('record_sec_press2_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('end_sec_press_time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 19, 45, 89991))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TimeApp.item')),
            ],
        ),
    ]
