# Generated by Django 4.0.5 on 2022-07-04 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=40)),
                ('init', models.IntegerField(blank=True, default=0, null=True)),
                ('kneader', models.IntegerField(blank=True, default=0, null=True)),
                ('extruder', models.IntegerField(blank=True, default=0, null=True)),
                ('prepress', models.IntegerField(blank=True, default=0, null=True)),
                ('m2_prim_press', models.IntegerField(blank=True, default=0, null=True)),
                ('primary_press', models.IntegerField(blank=True, default=0, null=True)),
                ('m2_sec_press', models.IntegerField(blank=True, default=0, null=True)),
                ('secpress1', models.IntegerField(blank=True, default=0, null=True)),
                ('secpress2', models.IntegerField(blank=True, default=0, null=True)),
                ('secpress3', models.IntegerField(blank=True, default=0, null=True)),
                ('mc_finish', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kneader_time', models.DateTimeField()),
                ('extruder_time', models.DateTimeField()),
                ('prepress_time', models.DateTimeField()),
                ('m2_prim_press_time', models.DateTimeField()),
                ('primary_press_time', models.DateTimeField()),
                ('m2_sec_press_time', models.DateTimeField()),
                ('secpress1_time', models.DateTimeField()),
                ('secpress2_time', models.DateTimeField()),
                ('secpress3_time', models.DateTimeField()),
                ('mc_finish_time', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TimeApp.item')),
            ],
        ),
    ]
