# Generated by Django 4.0.5 on 2022-07-04 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extra2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extra3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='extra1_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AddField(
            model_name='lot',
            name='extra2_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AddField(
            model_name='lot',
            name='extra3_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='extruder_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='kneader_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='m2_prim_press_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='m2_sec_press_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='mc_finish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='prepress_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='primary_press_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='secpress1_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='secpress2_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='secpress3_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 12, 40, 51790)),
        ),
    ]
